# roles/go-ipfs/tasks/install.yml
---
  #- name: "Centos: Install packages"
  #  yum:
  #    name: "golang"
  #    state: "latest"
  #  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

  - name: "Extracting go-ipfs archive"
    ansible.builtin.unarchive:
      src: "https://dist.ipfs.io/go-ipfs/{{ ipfs_version }}/go-ipfs_{{ ipfs_version }}_linux-amd64.tar.gz"
      dest: "/opt"
      remote_src: "yes"
      validate_certs: "no"

  - name: "Installing go-ipfs"
    shell: "bash /opt/go-ipfs/install.sh"
